<?php
/*
 *  create database tables and columns
 */
function tripal_diamond_install()
{
    return null;
}

function tripal_diamond_schema()
{
    $schema['diamond_jobs'] = array(
        'description' => t('Tripal Diamond Jobs'),
        'fields' => array(
            'job_id' => array(
                'description' => t('Primary key'),
                'type' => 'serial',
                'unsigned' => true,
                'not null' => true,
            ),
            'tripal_job_id' => array(
                'description' => t('Tied to Tripal Job ID'),
                'type' => 'int',
                'unsigned' => true,
                'not null' => true,
            ),
            'name' => array(
                'description' => t('name of job'),
                'type' => 'serial',
                'unsigned' => true,
                'not null' => true,
            ),
            'submitter' => array(
                'description' => t('user who submitted the job'),
                'type' => 'varchar',
                'length' => 15,
                'not null' => true,
            ),
            'status' => array(
                'description' => t('status of the job'),
                'type' => 'varchar',
                'length' => 15,
                'not null' => true,
            ),
            'last_check' => array(
                'description' => t('time of last progress check'),
                'type' => 'int',
                'unsigned' => true,
                'not null' => true,
            ),
            'progress' => array(
                'description' => t('progress of job at last check'),
                'type' => 'varchar',
                'length' => 15,
                'not null' => true,
            ),
            'start_date' => array(
                'description' => t('date when the job was initiated'),
                'type' => 'varchar',
                'length' => '15',
                'not null' => true,
            ),
            'end_date' => array(
                'description' => t('date when the job was ended (after last check aka first /complete/ check'),
                'type' => 'varchar',
                'length' => 15,
                'not null' => true,
            ),
        ),
    );
            
    $schema['diamond_job_information'] = array(
        'description' => t('Tripal Diamond Job Information'),
        'fields' => array(
            'jid' => array(
                'description' => t('Primary key'),
                'type' => 'serial',
                'unsigned' => true,
                'not null' => true,
            ),
            'tripal_job_id' => array(
                'description' => t('Tied to Tripal Job ID'),
                'type' => 'int',
                'unsigned' => true,
                'not null' => true,
            ),
            'name' => array(
                'description' => t('name of job'),
                'type' => 'serial',
                'unsigned' => true,
                'not null' => true,
            ),
            'command' => array(
                'description' => t('the command that was assembled to run remotely'),
                'type' => 'varchar',
                'length' => 255,
                'not null' => true,
            ),
            'files' => array(
                'description' => t('files to be included in running the job'),
                'type' => 'varchar',
                'length' => 255,
                'not null' => true,
            ),
            'included_db' => array(
                'description' => t('pre-existing database (if used)'),
                'type' => 'varchar',
                'length' => 255,
                'not null' => false,
            ),
        ),
    );
    
    $schema['diamond_db_existing_locations'] = array(
        'description' => t('Tripal Diamond Database Locations for Pre-existing databases'),
        'fields' => array(
            'db_id' => array(
                'description' => t('ID of the database (autoincrement)'),
                'type' => 'serial',
                'not null' => true,
            ),
            'type' => array(
                'description' => t('Type of Database (Protein or Nucleotide)'),
                'type' => 'varchar',
                'length' => 31,
                'not null' => true,                
            ),
            'name' => array(
                'description' => t('Name of the database'),
                'type' => 'varchar',
                'length' => 255,
                'not null' => true,
            ),
            'version' => array(
                'description' => t('Version of the stored database'),
                'type' => 'varchar',
                'length' => 31,
            ),
            'location' => array(
                'description' => t('Location on disk where the database file exists'),
                'type' => 'varchar',
                'length' => 512,
                'not null' => true,
            ),
        ),
    );
    
   return $schema;         
}

