<?php
error_reporting(E_ALL);
/**
 *    Let's include some files
 */
// Admin 
require_once 'includes/admin/tripal_diamond.dblist.inc';
require_once 'includes/admin/tripal_diamond.settings.inc';
require_once 'includes/admin/tripal_diamond.categories.inc';

// Classes
require_once 'includes/tripal_diamond_databases.inc';

// API
require_once 'api/tripal_diamond.api.inc';

// Forms (allow for more than just basic form)
require_once 'includes/tripal_diamond_submit.form.inc';

// Theme
require_once 'theme/tripal_diamond.theme.inc';

// Output
require_once 'includes/tripal_diamond.review.inc';
require_once 'includes/tripal_diamond.download.inc';

// Permissions
function tripal_diamond_permission() {
  return array (
    'administer diamond' => array (
      'title' => t ( 'Administer Diamond Module' ),
      'description' => t ( 'Allows a user to modify the list of databases available for the user to Diamond/BLAST against' )
    ),
  );
}

function tripal_diamond_init()
{
}

/*
 * Generate the links for the module
 */
function tripal_diamond_menu()
{
    $items = array();
    
    // Diamond Job submission form (for URL)
    $items['TSeq/submit'] = array(
        'title' => 'Sequence Similarity Search: Diamond/BLAST',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('tseq_submit_form'),
        'access callback' => TRUE,
        'access arguments' => array('access content'),
        'type' => MENU_NORMAL_ITEM,
        );
        
    // Diamond Results page
    $items['TSeq/results/%'] = array(
        'title' => 'Diamond Job Results',
        'page callback' => 'tseq_review',
        'page arguments' => array(2),
        'access callback' => TRUE,
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK
        );
    
    // Diamond Download page
    $items['TSeq/results/download/%/%'] = array(
        'title' => 'TSeq Job Results Download',
        'page callback' => 'tseq_download',
        'page arguments' => array(3,4),
        'access callback' => TRUE,
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK
        );
        
    // Configuration page
    $items['admin/tripal/extension/tseq/config'] = array(
        'title' =>  'TSeq Configuration',
        'description'   =>  'Configuration for the Tripal Diamond module',
        'page callback' => 'tseq_config_page_build',
        'page arguments'=>  array('1','tseq_config_page'),
        'type'  =>  MENU_NORMAL_ITEM,
        'file'  =>  'includes/admin/tripal_diamond.dblist.inc',
        'file path'     =>  drupal_get_path('module','tripal_diamond'),
        'access callback' => TRUE,
        'access arguments' => array('administer diamond'),
    );
    
    // Configuration: Database list, first page
    $items['admin/tripal/extension/tseq/config/dblist'] = array(
        'title' => 'Existing Database List',
        'description' => 'Tripal Diamond Admin Configuration page',
        'page callback' => 'tseq_config_page_build',
        'page arguments' => array('1','tseq_config_page'),
        'access callback' => TRUE,
        'access arguments' => array('administer diamond'),
        'type' => MENU_DEFAULT_LOCAL_TASK ,
        'file' => 'includes/admin/tripal_diamond.dblist.inc',
        'file path' => drupal_get_path ('module', 'tripal_diamond')
        );
    
    // Configuration: Database list, specified page
    $items['admin/tripal/extension/tseq/config/dblist/%'] = array(
        'title' => 'TSeq Configuration',
        'description' => 'Tripal Diamond Admin Configuration page',
        'page callback' => 'tseq_config_page_build',
        'page arguments' => array(6,'tseq_config_page'),
        'access callback' => TRUE,
        'access arguments' => array('administer diamond'),
        'type' => MENU_NORMAL_ITEM,
        'file' => 'includes/admin/tripal_diamond.dblist.inc',
        'file path' => drupal_get_path ('module', 'tripal_diamond')
        );
    
    // Configuration: Settings Tab
    $items['admin/tripal/extension/tseq/config/settings'] = array(
        'title' => 'Settings',
        'type'  => MENU_LOCAL_TASK,
        'weight' => 1,
        'priority' => 1,
        'page callback' =>  'drupal_get_form',
        'page arguments'=>  array('tseq_configuration_settings_form'),
        'access callback' => TRUE,
        'access arguments' => array('administer diamond'),
        'file' => 'includes/admin/tripal_diamond.settings.inc',
        'file path' => drupal_get_path ('module', 'tripal_diamond')
    );
    
    // Configuration: Defaults Tab
    $items['admin/tripal/extension/tseq/config/defaults'] = array(
        'title' => 'Advanced Options - Defaults',
        'type'  => MENU_LOCAL_TASK,
        'weight' => 2,
        'priority' => 2,
        'page callback' =>  'drupal_get_form',
        'page arguments'=>  array('tseq_configuration_defaults_form'),
        'access callback' => TRUE,
        'access arguments' => array('administer diamond'),
        'file' => 'includes/admin/tseq.defaults.inc',
        'file path' => drupal_get_path ('module', 'tripal_diamond')
    );
    
    //Configuration: Categories Tab
    $items['admin/tripal/extension/tseq/config/categories'] = array(
        'title' => 'Categories',
        'type'  => MENU_LOCAL_TASK,
        'weight' => 3,
        'priority' => 3,
        'page callback' =>  'tseq_config_categories_page_build',
        'page arguments'=>  array('1', 'tseq_config_categories_page'),
        'access callback' => TRUE,
        'access arguments' => array('administer diamond'),
        'file' => 'includes/admin/tripal_diamond.categories.inc',
        'file path' => drupal_get_path ('module', 'tripal_diamond')
    );
    
    //Admin: Genome Browser Link Scheme Tab
    $items['admin/tripal/extension/tseq/config/browseLink'] = array(
        'title' => 'Genome Browser Link',
        'type'  => MENU_LOCAL_TASK,
        'weight' => 4,
        'priority' => 4,
        'page callback' =>  'tseq_config_browseLink_page_build',
        'page arguments'=>  array('1', 'tseq_config_browseLink_page'),
        'access callback' => TRUE,
        'access arguments' => array('administer diamond'),
        'file' => 'includes/admin/tseq.browseLink.inc',
        'file path' => drupal_get_path ('module', 'tripal_diamond')
    );
    
    // Admin: add a new target database
    $items['admin/tripal/extension/tseq/add_db'] = array(
        'title' => 'Add Target Database',
        'description' => 'Tripal Diamond Admin Configuration page',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('tseq_database_add_form',5),
        'access callback' => TRUE,
        'access arguments' => array('administer diamond'),
        'type' => MENU_CALLBACK,
        );
    
    // Admin: edit an existing database
    $items['admin/tripal/extension/tseq/edit_db/%'] = array(
        'title' => 'Tripal Diamond Database Edit',
        'description' => 'Tripal Diamond Admin Configuration page',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('tseq_database_edit_form',5),
        'access callback' => TRUE,
        'access arguments' => array('administer diamond'),
        'type' => MENU_CALLBACK
        );
    // Admin: delete an existing database
    $items['admin/tripal/extension/tseq/delete_db/%'] = array(
        'title' => 'Tripal Diamond Database Delete',
        'description' => 'Tripal Diamond Admin Configuration page',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('tseq_database_delete_form', 5),
        'access callback' => TRUE,
        'access arguments' => array('administer diamond'),
        'type' => MENU_CALLBACK
        );
    /*
     *  Add/Edit/Delete Categories
     */
    // Admin: add a new category
    $items['admin/tripal/extension/tseq/add_category'] = array(
        'title' => 'Add Category',
        'description' => 'Tripal Diamond Admin Configuration page',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('tseq_category_add_form',5),
        'access callback' => TRUE,
        'access arguments' => array('administer diamond'),
        'type' => MENU_CALLBACK,
        );
   // Admin: edit an existing category
    $items['admin/tripal/extension/tseq/edit_category/%'] = array(
        'title' => 'Tripal Diamond Category Edit',
        'description' => 'Tripal Diamond Admin Configuration page',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('tseq_category_edit_form',5),
        'access callback' => TRUE,
        'access arguments' => array('administer diamond'),
        'type' => MENU_CALLBACK
        );
    // Admin: delete an existing category
    $items['admin/tripal/extension/tseq/delete_category/%'] = array(
        'title' => 'Tripal Diamond Database Delete',
        'description' => 'Tripal Diamond Admin Configuration page',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('tseq_category_delete_form', 5),
        'access callback' => TRUE,
        'access arguments' => array('administer diamond'),
        'type' => MENU_CALLBACK
        );
    
    /*
    // Admin: add a new Genome Browser Link Scheme
    $items['admin/tripal/extension/diamond/add_browseLink'] = array(
        'title' => 'TSeq Genome Browser Link Scheme Add',
        'description' => 'Tripal Diamond Admin Configuration page',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('tseq_browseLink_add_form',5),
        'access callback' => TRUE,
        'access arguments' => array('administer diamond'),
        'type' => MENU_CALLBACK,
        );
    
    // Admin: edit an existing Genome Browser Link Scheme
    $items['admin/tripal/extension/diamond/edit_browseLink/%'] = array(
        'title' => 'TSeq Genome Browser Link Scheme Edit',
        'description' => 'Tripal Diamond Admin Configuration page',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('tseq_browseLink_edit_form',5),
        'access callback' => TRUE,
        'access arguments' => array('administer diamond'),
        'type' => MENU_CALLBACK
        );
    // Admin: delete an existing Genome Browser Link Scheme
    $items['admin/tripal/extension/diamond/delete_browseLink/%'] = array(
        'title' => 'TSeq Genome Browser Link Scheme Delete',
        'description' => 'Tripal Diamond Admin Configuration page',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('tseq_browseLink_delete_form', 5),
        'access callback' => TRUE,
        'access arguments' => array('administer diamond'),
        'type' => MENU_CALLBACK
        );
    
     * 
     */
    //Test for Analyses Page
    $items['user/%/tseq_analysis'] = array (
        'title' => 'TSeq Analysis',
        'description' => 'Show results of Diamond or BLAST jobs belonging to the user',
        'page callback' => 'tseq_user_analysis_page',
        'page arguments' => array(1),
        'access callback' => TRUE,
        'type' => MENU_LOCAL_TASK,
        'file' => 'includes/tripal_diamond.user.inc',
        'file path' => drupal_get_path('module', 'tripal_diamond'),
    );
    
    //Admin: Export the database list
    /*$items['admin/tripal/extension/diamond/export'] = array(
        'title' => 'Tripal Diamond Database Export',
        'description' => 'Export the database list to a CSV file for backup/transfer',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('tripal_diamond_database_export_form'),
        'access callback' => TRUE,
        'access arguments' => array('administer diamond'),
        'type' => MENU_NORMAL_ITEM
        );
    
    //Admin: Import a saved database list
    $items['admin/tripal/extension/diamond/import'] = array(
        'title' => 'Tripal Diamond Database Import',
        'description' => 'Import to the database list from a CSV file',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('tripal_diamond_database_import_form'),
        'access callback' => TRUE,
        'access arguments' => array('administer diamond'),
        'type' => MENU_NORMAL_ITEM
        );
     * 
     */
    
    
    
    return $items;
}


function tripal_diamond_theme()
{
  $items = array();
  $path = drupal_get_path('module', 'tripal_diamond');

  // Displays the BLAST results for each job
  $items['tripal_diamond_results'] = array(
    'template' => 'tripal_diamond_review',
    'path' => "$path/theme",
  );
 return $items;
}


/*
 *  Email to users
 */

function tripal_diamond_mail($key, &$message, $params) {
  $site_name = variable_get('site_name', "");
  
  /*
  * Get information from the job (tseq_job_information)
  */
  
  switch ($key) {
    case 'job-complete':
      #if (!"test_for_error")
      
      /*$job     = $params['job'];
      $user    = $params['user'];
      $message['subject'] = t("Your $site_name job: " . $job->getJobName());
      $message['body'][] = "Your job titled \"" . $job->getJobName() . "\", has completed.";
      $message['body'][] = "Please return to $site_name site to view the results for this job.";
      break;
      */
    case 'job-started':
        /*
      $job  = $params['job'];
      $user = $params['user'];
      $message['subject'] = t("Your $site_name job has started: " . $job->getJobName());
      $message['body'][] = "Your job titled \"" . $job->getJobName() . "\" " .
      $message['body'][] = "You will receive an email once the job has completed.";
      break;
      */
    case 'job-error':
      $message['subject'] = t("This is a test");
      $message['body'][] = "This has been a test.";
      break;
  }
}